name: deploy_frontend
# Deploys when push is made from frontend folder

on:
    push:
        branches: [ master ]
        paths:
            - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account set --subscription "2d83dcf9-9266-4b8f-b2d7-7cfc71e136e3"
            az storage blob upload-batch --auth-mode key -d '$web' -s frontend/ --account-name cloudportfolio
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "cloud-portfolio" --name "cloud-portfolio" --resource-group "cloud-portfolio"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
